Repository nasa-gibs/worldview-options-eosdis, pull requests merged in 2018-07, with the labels that each got.

#218 Replace favicon to remove white border
  common/brand/images/wv-icon.ico
Labels: bug, under development

#219 Remove warnings when GIBS layers are not used
  release/config.json
Labels: ready for review, technical

#228 added IMERG description/references
  common/config/metadata/multi-mission/imerg/IMERG_Rain_Rate.md
  common/config/metadata/multi-mission/imerg/IMERG_Snow_Rate.md
  common/config/wv.json/layers/multi-mission/imerg/IMERG_Rain_Rate.json
  common/config/wv.json/layers/multi-mission/imerg/IMERG_Snow_Rate.json
Labels: under development

#227 Remove grid cell value content from flood hazard metadata
  common/config/metadata/sedac/FloodHazard.md
  common/config/metadata/sedac/NDH_Flood_Hazard_Frequency_Distribution_1985-2003.md
Labels: ready for review

#220 Immutable palettes
  common/config/wv.json/layers/landsat/Landsat_WELD_CONUS_5_Year_Tree_Cover.json
Labels: under development

#230 v2.13.0
  package-lock.json
  package.json
Labels: under development

#221 Remove about.md
  common/brand/pages/about.md
Labels: under development
